# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 024d708d72f516dc25a4da3dc4135510b6d3636f7f2c848aeee3c3aa62bb9a16572accc60be850cf94143ebd41e62d6c334b34ef4bf5391f8c9abd4c6e20b821

test:
  secret_key_base: 17f8f55e2f405c4c1f11d34db0ebbb466409d20db0b8bf16614cd4e11b616f03f607b35ca4b43e8ff189ddbf7131edc60f24dbb95ddac63ad3d5f8bb4257f72e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
